Repository uber/nebula.gl, pull requests merged in 2018-07, with the labels that each got.

#20 Draw LineStrings
  docs/api-reference/layers/editable-geojson-layer.md
  docs/overview.md
  examples/deck/example.js
  src/lib/editable-feature-collection.js
  src/lib/layers/editable-geojson-layer.js
  src/lib/layers/editable-layer.js
  src/test/lib/editable-feature-collection.test.js
Labels: documentation, feature

#24 fix travis-ci to run ALL tests
  package.json
  src/lib/curve-utils.js
  src/lib/editable-feature-collection.js
  src/lib/layers/editable-geojson-layer.js
  src/lib/layers/editable-layer.js
  src/lib/nebula-react.js
  src/lib/nebula.js
  src/test/lib/layers/texts-layer.test.js
  src/test/lib/overlays/html-tooltip-overlay.test.js
  src/types.js
  yarn.lock
Labels: bug

#29 Homepage "Hero" with Demo
  .flowconfig
  examples/deck/package.json
  examples/deck/yarn.lock
  website/src/components/Hero.js
  website/src/styles/index.scss
Labels: documentation

#33 Support for (and default to) dashed lines
  docs/api-reference/layers/editable-geojson-layer.md
  examples/deck/example.js
  examples/deck/package.json
  examples/deck/yarn.lock
  src/lib/layers/editable-geojson-layer.js
Labels: feature
