Repository uber/nebula.gl, pull requests merged in 2019-01, with the labels that each got.

#147 Allow using custom options object to use for supercluster instantiation
  docs/api-reference/overlays/html-cluster-overlay.md
  modules/react/src/lib/overlays/html-cluster-overlay.js
Labels: feature

#151 Fix changelog
  CHANGELOG.md
Labels: documentation

#156 Fix issue with clicking edit handle while drawing polygon
  modules/core/src/lib/mode-handlers/draw-polygon-handler.js
Labels: bug
